### ISSUE TITLE
unhandledRejection in ntlmAuthXhrApi

### ISSUE THREAD

**Issue by thlee927** [gautamsi/ews-javascript-api-auth#5]
I am writing an application to retrieve some emails from a mailbox.
I use "Folder.FindItems" function to search the email items, then loop the search result and bind the EmailMessage. 
But our exchange server is not stable. It may throw "connect ECONNREFUSED " error when I bind over 4000 emails.
I would like to catch the error and retry the bind function. 
But "ntlmAuthXhrApi.xhr" did not catch the error.
When the mail server throw any error, the application will stop at here. 
Could you please change the code to catch the error?

Error Log:
```
2017-07-20T10:21:06.405Z - error:  Error: connect ECONNREFUSED XXX.XXX.XXX.XXX:443
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1096:14)
From previous event:
    at ntlmAuthXhrApi.ntlmPreCall (/home/uat/CX/cx_omnichannel_email_extract/node_modules/ews-javascript-api-auth/src/ntlmAuthXhrApi.js:122:16)
    at ntlmAuthXhrApi.xhr (/home/uat/CX/cx_omnichannel_email_extract/node_modules/ews-javascript-api-auth/src/ntlmAuthXhrApi.js:44:19)
From previous event:
    at ntlmAuthXhrApi.xhr (/home/uat/CX/cx_omnichannel_email_extract/node_modules/ews-javascript-api-auth/src/ntlmAuthXhrApi.js:43:16)
    at GetItemRequest.ServiceRequestBase.ValidateAndEmitRequest (/home/uat/CX/cx_omnichannel_email_extract/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:408:36)
    at SimpleServiceRequestBase.InternalExecute (/home/uat/CX/cx_omnichannel_email_extract/node_modules/ews-javascript-api/js/Core/Requests/SimpleServiceRequestBase.js:50:19)
From previous event:
    at GetItemRequest.SimpleServiceRequestBase.InternalExecute (/home/uat/CX/cx_omnichannel_email_extract/node_modules/ews-javascript-api/js/Core/Requests/SimpleServiceRequestBase.js:47:16)
    at MultiResponseServiceRequest.Execute (/home/uat/CX/cx_omnichannel_email_extract/node_modules/ews-javascript-api/js/Core/Requests/MultiResponseServiceRequest.js:45:19)
From previous event:
    at GetItemRequest.MultiResponseServiceRequest.Execute (/home/uat/CX/cx_omnichannel_email_extract/node_modules/ews-javascript-api/js/Core/Requests/MultiResponseServiceRequest.js:44:16)
    at ExchangeService.InternalBindToItems (/home/uat/CX/cx_omnichannel_email_extract/node_modules/ews-javascript-api/js/Core/ExchangeService.js:656:24)
    at ExchangeService.BindToItem (/home/uat/CX/cx_omnichannel_email_extract/node_modules/ews-javascript-api/js/Core/ExchangeService.js:438:21)
    at Function.EmailMessage.Bind (/home/uat/CX/cx_omnichannel_email_extract/node_modules/ews-javascript-api/js/Core/ServiceObjects/Items/EmailMessage.js:277:24)
    at _loadEmailInFolder (/home/uat/CX/cx_omnichannel_email_extract/app/facade/email-extraction-server-facade.js:1261:60)

```
Example:

**ews-javascript-api-auth/src/ntlmAuthXhrApi.js**
```
    ntlmAuthXhrApi.prototype.xhr = function (xhroptions, progressDelegate) {
        var _this = this;
        //setup xhr for github.com/andris9/fetch options
        var options = {
            url: xhroptions.url,
            //payload: xhroptions.data,
            headers: xhroptions.headers,
            method: 'GET',
            agent: new https_1.Agent({ keepAlive: true, rejectUnauthorized: !this.allowUntrustedCertificate }) //keepaliveAgent
        };

        return new Promise(function (resolve, reject) {
            _this.ntlmPreCall(options).then(function (optionsWithNtlmHeader) {
                optionsWithNtlmHeader['payload'] = xhroptions.data;
                optionsWithNtlmHeader['method'] = xhroptions.type;
                fetch_1.fetchUrl(xhroptions.url, optionsWithNtlmHeader, function (error, meta, body) {
                    if (error) {
                        reject(error);
                    }
                    else {
                        var xhrResponse = {
                            response: body.toString(),
                            status: meta.status,
                            redirectCount: meta.redirectCount,
                            headers: meta.responseHeaders,
                            finalUrl: meta.finalUrl,
                            responseType: '',
                            statusText: undefined,
                        };

                        if (xhrResponse.status === 200) {
                            resolve(utils_1.setupXhrResponse(xhrResponse));
                        }
                        else {
                            reject(utils_1.setupXhrResponse(xhrResponse));
                        }
                    }
                });
            });
        });
    };
```
Change to:

```

    ntlmAuthXhrApi.prototype.xhr = function (xhroptions, progressDelegate) {
        var _this = this;
        //setup xhr for github.com/andris9/fetch options
        var options = {
            url: xhroptions.url,
            //payload: xhroptions.data,
            headers: xhroptions.headers,
            method: 'GET',
            agent: new https_1.Agent({ keepAlive: true, rejectUnauthorized: !this.allowUntrustedCertificate }) //keepaliveAgent
        };

        return new Promise(function (resolve, reject) {
            _this.ntlmPreCall(options).then(function (optionsWithNtlmHeader) {
                optionsWithNtlmHeader['payload'] = xhroptions.data;
                optionsWithNtlmHeader['method'] = xhroptions.type;
                fetch_1.fetchUrl(xhroptions.url, optionsWithNtlmHeader, function (error, meta, body) {
                    if (error) {
                        reject(error);
                    }
                    else {
                        var xhrResponse = {
                            response: body.toString(),
                            status: meta.status,
                            redirectCount: meta.redirectCount,
                            headers: meta.responseHeaders,
                            finalUrl: meta.finalUrl,
                            responseType: '',
                            statusText: undefined,
                        };

                        if (xhrResponse.status === 200) {
                            resolve(utils_1.setupXhrResponse(xhrResponse));
                        }
                        else {
                            reject(utils_1.setupXhrResponse(xhrResponse));
                        }
                    }
                });
            }).catch(function(err){
                reject(err);
            });
        });
    };
```

**ews-javascript-api/js/Core/Requests/SimpleServiceRequestBase.js**
```
SimpleServiceRequestBase.prototype.InternalExecute = function () {
        //var writer = new Data.EwsServiceXmlWriter();
        //this.WriteSoapRequest(this.url, writer);
        var _this = this;
        //if (!this.Service && !this.Service.Credentials && (!this.Service.Credentials.UserName || this.service.Credentials.Password))
        //    throw new Error("missing credential");
        //var cred = "Basic " + btoa(this.Service.Credentials.UserName + ":" + this.Service.Credentials.Password);
        //var cc = writer.GetXML();
        //var xhrOptions: IXHROptions = {
        //    type: "POST",
        //    data: cc,
        //    url: "https://pod51045.outlook.com/autodiscover/autodiscover.svc",
        //    headers: { "Content-Type": "text/xml", "Authorization": cred },
        //    //customRequestInitializer: function (x) {
        //    //    var m = x;
        //    //}
        //};

        return new Promise_1.Promise(function (successDelegate, errorDelegate) {
            var request = _this.BuildXHR();
            //this.ReadResponsePrivate(response);
            _this.ValidateAndEmitRequest(request).then(function (xhrResponse) {
                var dom = new ExtensionMethods_1.DOMParser();
                var xml2js = new ExtensionMethods_1.xml2JsObject();
                var req = xml2js.parseXMLNode(dom.parseFromString(request.data, "text/xml").documentElement, true);
                EwsLogging_1.EwsLogging.DebugLog(req, true);

                if (xhrResponse.status == 200) {
                    EwsLogging_1.EwsLogging.DebugLog(xhrResponse, true);
                    var ewsXmlReader = new EwsServiceXmlReader_1.EwsServiceXmlReader(xhrResponse.responseText || xhrResponse.response, _this.Service);
                    //EwsLogging.DebugLog(ewsXmlReader.JsObject, true);
                    var serviceResponse = _this.ReadResponsePrivate(ewsXmlReader.JsObject);
                    if (successDelegate)
                        successDelegate(serviceResponse || xhrResponse.responseText || xhrResponse.response);
                }
                else {
                    if (errorDelegate)
                        errorDelegate(_this.ProcessWebException(serviceResponse || xhrResponse.responseText || xhrResponse.response) || serviceResponse);
                }
            }, function (resperr) {
                EwsLogging_1.EwsLogging.Log("Error in calling service, error code:" + resperr.status + "\r\n" + resperr.getAllResponseHeaders());
                if (errorDelegate)
                    errorDelegate(_this.ProcessWebException(resperr) || resperr);
            });
        });
    };
```

Change To:
```

SimpleServiceRequestBase.prototype.InternalExecute = function () {
        //var writer = new Data.EwsServiceXmlWriter();
        //this.WriteSoapRequest(this.url, writer);
        var _this = this;
        //if (!this.Service && !this.Service.Credentials && (!this.Service.Credentials.UserName || this.service.Credentials.Password))
        //    throw new Error("missing credential");
        //var cred = "Basic " + btoa(this.Service.Credentials.UserName + ":" + this.Service.Credentials.Password);
        //var cc = writer.GetXML();
        //var xhrOptions: IXHROptions = {
        //    type: "POST",
        //    data: cc,
        //    url: "https://pod51045.outlook.com/autodiscover/autodiscover.svc",
        //    headers: { "Content-Type": "text/xml", "Authorization": cred },
        //    //customRequestInitializer: function (x) {
        //    //    var m = x;
        //    //}
        //};

        return new Promise_1.Promise(function (successDelegate, errorDelegate) {
            var request = _this.BuildXHR();
            //this.ReadResponsePrivate(response);
            _this.ValidateAndEmitRequest(request).then(function (xhrResponse) {
                var dom = new ExtensionMethods_1.DOMParser();
                var xml2js = new ExtensionMethods_1.xml2JsObject();
                var req = xml2js.parseXMLNode(dom.parseFromString(request.data, "text/xml").documentElement, true);
                EwsLogging_1.EwsLogging.DebugLog(req, true);

                if (xhrResponse.status == 200) {
                    EwsLogging_1.EwsLogging.DebugLog(xhrResponse, true);
                    var ewsXmlReader = new EwsServiceXmlReader_1.EwsServiceXmlReader(xhrResponse.responseText || xhrResponse.response, _this.Service);
                    //EwsLogging.DebugLog(ewsXmlReader.JsObject, true);
                    var serviceResponse = _this.ReadResponsePrivate(ewsXmlReader.JsObject);
                    if (successDelegate)
                        successDelegate(serviceResponse || xhrResponse.responseText || xhrResponse.response);
                }
                else {
                    if (errorDelegate)
                        errorDelegate(_this.ProcessWebException(serviceResponse || xhrResponse.responseText || xhrResponse.response) || serviceResponse);
                }
            }, function (resperr) {
                EwsLogging_1.EwsLogging.Log("Error in calling service, error code:" + resperr.status + "\r\n" + ((resperr.getAllResponseHeaders)?resperr.getAllResponseHeaders():""));
                if (errorDelegate)
                    errorDelegate(_this.ProcessWebException(resperr) || resperr);
            });
        });
    };
```

**Comment by gautamsi** [comment]
@thlee927  the pull was merged. is it still an issue?
